### ISSUE TITLE
dribbble_config_play.properties (系统找不到指定的文件。)

### ISSUE THREAD

**Issue by LegendBMKill** [gejiaheng/Protein#4]

**Comment by yangzixiao** [comment]
the same issue

**Comment by yangzixiao** [comment]
编译时报错，Error:(66, 0) dribbble_config_play.properties (系统找不到指定的文件。)
<a href="openFile:C:\android\master\Protein-master\Protein-master\app\build.gradle">Open File</a>

**Comment by gokulkrizh** [comment]
@LegendBMKill  how do you solve this issue

**Comment by gejiaheng** [comment]
Sorry, it's my fault. I only tested deleting the *dribbble_config_play.properties* within the original project, but not a clean repo cloned from GitHub. 
I've updated the project. You should be good to go now.
