### ISSUE TITLE
On Library List CustomTab cannot open

### ISSUE THREAD

**Issue by Cutta** [gejiaheng/Protein#9]
Under Licenses on Library list click item cause this error.
`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsIntent$Builder;`
I noticed that the other library is yours too :) Congrats .Good job but CusTomTabs throw exception.

**Comment by gejiaheng** [comment]
@Cutta 
Thanks for reporting this. I'll fix it today.

**Comment by gejiaheng** [comment]
@Cutta 
Seems that I can't fix it today. Have you tried clean and rebuild the project? Are you still having this crash? If you are still having it, would you please tell me your phone brand and os version?

**Comment by gejiaheng** [comment]
https://github.com/gejiaheng/Protein/commit/217a7aa36747f97f859f2a7fc3321f825b89ad7b
